spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/api?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat,wall,slf4j,default
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #forbidden HTML to Reset all
        reset-enable: false
        login-username: msc
        login-password: ym
        #allow look:127.0.0.1:port/druid/index.html this is a white name list
        allow: 120.27.229.80,127.0.0.1
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-log-enabled: false
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-log-enabled: false
